// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from "@tuyau/utils/types";
import type { InferInput } from "@vinejs/vine/types";

type SignupGetHead = {
  request: unknown;
  response: MakeTuyauResponse<
    import("../app/controllers/signup_controller.ts").default["show"],
    false
  >;
};
type SignupPost = {
  request: MakeTuyauRequest<
    InferInput<typeof import("../app/validators/signup.ts")["signupValidator"]>
  >;
  response: MakeTuyauResponse<
    import("../app/controllers/signup_controller.ts").default["store"],
    true
  >;
};
export interface ApiDefinition {
  signup: {
    $url: {};
    $get: SignupGetHead;
    $head: SignupGetHead;
    $post: SignupPost;
  };
}
const routes = [
  {
    params: ["*"],
    name: "drive.fs.serve",
    path: "/uploads/*",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "home",
    path: "/",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "signup.show",
    path: "/signup",
    method: ["GET", "HEAD"],
    types: {} as SignupGetHead,
  },
  {
    params: [],
    name: "signup.store",
    path: "/signup",
    method: ["POST"],
    types: {} as SignupPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition,
};
declare module "@tuyau/inertia/types" {
  type InertiaApi = typeof api;
  export interface Api extends InertiaApi {}
}
