// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from "@tuyau/utils/types";
import type { InferInput } from "@vinejs/vine/types";

type StreamGetHead = {
  request: unknown;
  response: MakeTuyauResponse<
    import("../app/controllers/home_controller.ts").default["stream"],
    false
  >;
};
type SignupGetHead = {
  request: unknown;
  response: MakeTuyauResponse<
    import("../app/controllers/signup_controller.ts").default["show"],
    false
  >;
};
type SignupPost = {
  request: MakeTuyauRequest<
    InferInput<typeof import("../app/validators/signup.ts")["signupValidator"]>
  >;
  response: MakeTuyauResponse<
    import("../app/controllers/signup_controller.ts").default["store"],
    true
  >;
};
type VerifyemailIdGetHead = {
  request: unknown;
  response: MakeTuyauResponse<
    import("../app/controllers/email_verifications_controller.ts").default["verify"],
    false
  >;
};
type VerifyemailResendPost = {
  request: unknown;
  response: MakeTuyauResponse<
    import("../app/controllers/email_verifications_controller.ts").default["resend"],
    false
  >;
};
export interface ApiDefinition {
  stream: {
    $url: {};
    $get: StreamGetHead;
    $head: StreamGetHead;
  };
  signup: {
    $url: {};
    $get: SignupGetHead;
    $head: SignupGetHead;
    $post: SignupPost;
  };
  "verify-email": {
    ":token": {
      $url: {};
      $get: VerifyemailIdGetHead;
      $head: VerifyemailIdGetHead;
    };
    resend: {
      $url: {};
      $post: VerifyemailResendPost;
    };
  };
}
const routes = [
  {
    params: ["*"],
    name: "drive.fs.serve",
    path: "/uploads/*",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "home",
    path: "/",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: [],
    name: "stream",
    path: "/stream",
    method: ["GET", "HEAD"],
    types: {} as StreamGetHead,
  },
  {
    params: [],
    name: "signup.show",
    path: "/signup",
    method: ["GET", "HEAD"],
    types: {} as SignupGetHead,
  },
  {
    params: [],
    name: "signup.store",
    path: "/signup",
    method: ["POST"],
    types: {} as SignupPost,
  },
  {
    params: [],
    name: "logout",
    path: "/logout",
    method: ["GET", "HEAD"],
    types: {} as unknown,
  },
  {
    params: ["token"],
    name: "email.verify",
    path: "/verify-email/:token",
    method: ["GET", "HEAD"],
    types: {} as VerifyemailIdGetHead,
  },
  {
    params: [],
    name: "email.resend",
    path: "/verify-email/resend",
    method: ["POST"],
    types: {} as VerifyemailResendPost,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition,
};
declare module "@tuyau/inertia/types" {
  type InertiaApi = typeof api;
  export interface Api extends InertiaApi {}
}
